### ISSUE TITLE
Hi HairConditioner

### ISSUE THREAD

**Issue by ossuruk3123** [HairConditioner/Minecraft-Java-Agent-Client#1]
Can you do a hack for an example?

**Comment by HairConditioner** [comment]
idk how to do hacks but here's a framework for what you wanna inject (add inside for loop - this was built off a MouseDelayFix module I wrote):

InsnList insnList = new InsnList();
        insnList.add(new VarInsnNode(Opcodes.ALOAD, 0));
        insnList.add(new TypeInsnNode(Opcodes.INSTANCEOF, "<obfuscated method name here>"));
        LabelNode label = new LabelNode();
        insnList.add(new JumpInsnNode(Opcodes.IFEQ, label));
        insnList.add(new VarInsnNode(Opcodes.ALOAD, 0));
        insnList.add(new VarInsnNode(Opcodes.FLOAD, 1));
        insnList.add(new MethodInsnNode(Opcodes.INVOKESPECIAL, "<obfuscated method name>", methodNode.name, methodNode.desc, false));
        insnList.add(new InsnNode(Opcodes.ARETURN));
        insnList.add(label);
        methodNode.instructions.insert(insnList);

**Comment by HairConditioner** [comment]
Closed
